create table public.offer_leads (
  id uuid primary key,
  contact_name text not null check (char_length(contact_name) between 2 and 100),
  contact_email text not null,
  contact_phone text,
  total_market_price_cents integer not null check (total_market_price_cents >= 0),
  total_offer_cents integer not null check (total_offer_cents >= 0),
  offer_rate numeric(5,4) not null check (offer_rate > 0 and offer_rate <= 1),
  priced_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table public.offer_lead_items (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.offer_leads(id) on delete cascade,
  card_id text not null,
  card_name text not null,
  quantity integer not null check (quantity between 1 and 99),
  market_price_cents integer not null check (market_price_cents >= 0),
  offer_price_cents integer not null check (offer_price_cents >= 0)
);

create index offer_lead_items_lead_id_idx on public.offer_lead_items(lead_id);

alter table public.offer_leads enable row level security;
alter table public.offer_lead_items enable row level security;

create or replace function public.create_offer_lead(
  p_id uuid,
  p_contact_name text,
  p_contact_email text,
  p_contact_phone text,
  p_total_market_price_cents integer,
  p_total_offer_cents integer,
  p_offer_rate numeric,
  p_priced_at timestamptz,
  p_items jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.offer_leads (
    id, contact_name, contact_email, contact_phone,
    total_market_price_cents, total_offer_cents, offer_rate, priced_at
  ) values (
    p_id, p_contact_name, p_contact_email, p_contact_phone,
    p_total_market_price_cents, p_total_offer_cents, p_offer_rate, p_priced_at
  );

  insert into public.offer_lead_items (
    lead_id, card_id, card_name, quantity, market_price_cents, offer_price_cents
  )
  select
    p_id, item->>'cardId', item->>'name',
    (item->>'quantity')::integer,
    (item->>'marketPriceCents')::integer,
    (item->>'offerPriceCents')::integer
  from jsonb_array_elements(p_items) item;
end;
$$;

revoke execute on function public.create_offer_lead(
  uuid, text, text, text, integer, integer, numeric, timestamptz, jsonb
) from public;
grant execute on function public.create_offer_lead(
  uuid, text, text, text, integer, integer, numeric, timestamptz, jsonb
) to service_role;
